[project]
name = "ssm"
version = "0.1.0"
description = "SSM shim"
requires-python = ">=3.8"

[build-system]
requires = [
    "setuptools>=45",
    "wheel",
    "Cython>=0.29"
]
build-backend = "setuptools.build_meta"
